// generated by postadd script
#include <stddef.h>
#include "moonbit_app.h"

void app_main()
{
    moonbit_runtime_init(0, NULL);
    moonbit_init();
    $username$hello$main$moonbit_main(0, NULL);
}
